---
# Dieses Playbook installiert Humhub f체r Brocko auf Ubuntu-Systemen

- name: Basiskonfiguration, welches f체r alle Server gilt.
  hosts: all
  remote_user: root
  roles:
    - common
  vars:
    ntpservers:
      - 0.de.pool.ntp.org
      - 1.de.pool.ntp.org
      - 2.de.pool.ntp.org
      - 3.de.pool.ntp.org

- name: Konfiguriere den Webserver, auf welchem das Humhub-Frontend l채uft.
  hosts: webservers
  remote_user: root
  roles:
    - web
  vars:
    letsencrypt_account_email: admin@bugabinga.net
    letsencrypt_http_auth: webroot
    letsencrypt_webroot_path: /var/www
    letsencrypt_webserver_groupname: www-data
    letsencrypt_dns_challenge: no
    webmaster: admin@bugabinga.net
    domain: brockonet.bugabinga.net
    user: humhub
    humhub_version: 1.3.11
    humhub_sha512: 94c1ba99bac20408ea34c79476a17e81a3aa66ee0ad47c626aeee37cf879cd45bce468d5c9e98044bb99e5f6b3e5f6d6cd9f162c48f842c8778881fe37fdbfc6


- name: Konfiguriere den Datenbankserver, auf welchem MySQL l채uft.
  hosts: dbservers
  remote_user: root
  roles:
    - db
  vars:
    mysqlservice: mysqld
    mysql_port: 3306
    dbuser: humhub
    dbname: humhub
