---
# Dieses Playbook installiert Humhub f체r Brocko auf Ubuntu-Systemen

- name: Basiskonfiguration, welches f체r alle Server gilt.
  hosts: all
  remote_user: root
  roles:
    - common

- name: Konfiguriere den Webserver, auf welchem das Humhub-Frontend l채uft.
  hosts: webservers
  remote_user: root
  roles:
    - web

- name: Konfiguriere den Datenbankserver, auf welchem MySQL l채uft.
  hosts: dbservers
  remote_user: root
  roles:
    - db