---
# Installiere MySQL und erzeuge DB-Nutzer mit korrekten Rechten.

- name: Installiere MySQL
  apt:
    name:
      - mysql-server
      - python-mysqldb

- name: Konfiguriere MySQL
  template: 
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
  - restart mysql

- name: Starte MySQL
  service:
    name: mysql
    state: started
    enabled: yes

- name: Erzeuge Datenbank
  mysql_db:
    name: "{{ dbname }}"
    collation: utf8mb4_unicode_ci
    encoding: utf8mb4  
    state: present

- name: Erzeuge Datenbankbenutzer
  mysql_user:
    name: "{{ dbuser }}"
    password: "{{ dbpassword }}"
    priv: "{{ dbname }}.*:SELECT/{{ dbname }}.*:INSERT/{{ dbname }}.*:DELETE/{{ dbname }}.*:UPDATE/{{ dbname }}.*:CREATE/{{ dbname }}.*:ALTER/{{ dbname }}.*:INDEX/{{ dbname }}.*:DROP/{{ dbname }}.*:REFERENCES"
    host: '%'
    state: present
