---
# Installation von Humhub

- name: Betriebssystem-Benutzer speziell für Humhub erzeugen
  user:
    comment: "Humhub User"
    name: "{{ user  }}"

- name: Humhub runterladen
  get_url: 
    url: https://humhub.org/download/start?version={{ humhub_version }}&type=tar.gz
    checksum: "sha512:{{ humhub_sha512 }}"
    dest: /tmp/humhub.tar.gz
    mode: 0600
    group: "{{ user }}"
    owner: "{{ user }}"

- name: Humhub entpacken
  unarchive:
    remote_src: yes
    src: /tmp/humhub.tar.gz
    dest: /home/{{ user }}
    creates: /home/{{ user }}/humhub-{{ humhub_version }}
    mode: 0600
    group: "{{ user }}"
    owner: "{{ user }}"

- name: Rechte auf Humhub-Dateien einrichten (schreibbare)
  file:
    path: "{{ item }}"
    group: www-data
    recurse: yes
    state: directory
  with_items:
    - /home/{{ user }}/humhub-{{ humhub_version }}/assets
    - /home/{{ user }}/humhub-{{ humhub_version }}/protected/config
    - /home/{{ user }}/humhub-{{ humhub_version }}/protected/modules
    - /home/{{ user }}/humhub-{{ humhub_version }}/protected/runtime
    - /home/{{ user }}/humhub-{{ humhub_version }}/uploads

- name: Rechte auf Humhub-Dateien einrichten (nicht schreibbare)
  file:
    path: "{{ item }}"
    group: "{{ user }}"
    owner: "{{ user }}"
    state: directory
  with_items:
    - /home/{{ user }}/humhub-{{ humhub_version }}/protected
    - /home/{{ user }}/humhub-{{ humhub_version }}/uploads/file

- name: Rechte auf Humhub-Dateien einrichten (ausführbare)
  file:
    path: /home/{{ user }}/humhub-{{ humhub_version }}/protected/yii
    mode: "+x"

- name: Abhängigkeiten von Humhub installieren
  apt:
    name:
      - php7.2
      - php7.2-gd
      - php7.2-curl
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-zip
      - php7.2-intl
      - php-imagick
      - php-apcu
      - libapache2-mod-php7.2
      - apache2

- name: Webserver konfigurieren
  template:
    src: humhub-site.conf.j2
    dest: /etc/apache2/sites-enabled/humhub-site.conf
  notify: reload httpd

- name: Alten Default-Vhost aus Apache2 entfernen
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload httpd

- name: Webserver einrichten
  apache2_module:
    name: "{{ item }}"
  with_items:
    - ssl
    - headers
    - php7.2
  notify: reload httpd

- name: Webserver service einschalten
  service:
    name: apache2
    state: started
    enabled: yes
