---
# Installation von Humhub

- name: Betriebssystem-Benutzer speziell f체r Humhub erzeugen
  user:
    comment: "Humhub User"
    name: humhub

- name: Humhub runterladen
  get_url: 
    url: https://humhub.org/download/start?version={{ humhub_version }}&type=tar.gz
    checksum: "sha512:{{ humhub_sha512 }}"
    dest: /home/{{ user }}/tmp
    mode: 0600
    group: {{ user }}
    owner: {{ user }}

- name: Humhub entpacken
  unarchive:
    remote_src: yes
    src: /home/{{ user }}/tmp/humhub-{{ humhub_version }}.tar.gz
    dest: /home/{{ user }}/app
    creates: /home/{{ user }}/app
    mode: 0600
    group: {{ user }}
    owner: {{ user }}

- name: Rechte auf Humhub-Dateien einrichten (schreibbare)
  file:
    path: "{{ item }}"
    group: www-data
    recurse: yes
    state: directory
  with-items:
    - /home/{{ user }}/app/assets
    - /home/{{ user }}/app/protected/config
    - /home/{{ user }}/app/protected/modules
    - /home/{{ user }}/app/protected/runtime
    - /home/{{ user }}/app/uploads

- name: Rechte auf Humhub-Dateien einrichten (nicht schreibbare)
  file:
    path: "{{ item }}"
    group: {{ user }}
    owner: {{ user }}
    state: directory
  with-items:
    - /home/{{ user }}/app/protected
    - /home/{{ user }}/app/uploads/file

- name: Rechte auf Humhub-Dateien einrichten (ausf체hrbare)
  file:
    path: /home/{{ user }}/app/protected/yii
    mode: "+x"

- name: Abh채ngigkeiten von Humhub installieren
  apt:
    name:
      - php7.2
      - php7.2-gd
      - php7.2-curl
      - php7.2-mbstring
      - php7.2-mysql
      - php7.2-zip
      - php7.2-intl
      - php-imagick
      - php-apcu
      - libapache2-mod-php7.2
      - apache2

- name: Webserver konfigurieren
  template:
    src: humhub-site.j2
    dest: /etc/apache2/sites-enabled/humhub-site
  notify: reload httpd

- name: Alten Default-Vhost aus Apache2 entfernen
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: reload httpd

- name: Webserver einrichten
  apache2_module:
    name: "{{ item }}"
  with-items:
    - ssl
    - headers
    - php
  notify: reload httpd

- name: Cronjob f체r neue SSL-Zertifikate 
  cron:
    job: certbot renew --quiet --post-hook "apachectl graceful"
    name: certbot_renew
    day: "30"