---
# Dieses Playbook gilt für alle Hosts. 

- name: Software Repositories von Ubuntu aktualisieren
  apt:
    update_cache: yes
    cache_valid_time: 1500
    autoclean: yes
    autoremove: yes

- name: Installiere NTP
  apt: 
    name: ntp
    state: present

- name: Konfiguriere NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

- name: Starte NTP
  service: 
    name: ntpd
    state: started 
    enabled: yes